services:
  fastapi:
    image: fastapi
    ports:
      - 8000:8000
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app

  streamlit:
    image: streamlit
    ports:
      - 8501:8501
    build: 
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: streamlit-app
    depends_on:
      - fastapi
    environment:
      - API_ENDPOINT=http://fastapi:8000/