services:

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5555:5000"
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /tmp/mlruns
    container_name: mlflow-tracking-server

  fastapi:
    image: fastapi
    ports:
      - 8000:8000
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    depends_on:
      - mlflow

  streamlit:
    image: streamlit
    ports:
      - 8501:8501
    build: 
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: streamlit-app
    depends_on:
      - fastapi
    environment:
      - API_ENDPOINT=http://fastapi:8000/